version: '3.7'

services:
  prefect:
    image: prefecthq/prefect:3.4.2-python3.11
    command: prefect server start
    container_name: prefect-server
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${PREFECT_DB_USER}:${PREFECT_DB_PW}@prefect_db:5432/${PREFECT_DB_NAME} # Needed if using postgres and not sqlite
      # - PREFECT_UI_API_URL=https://localhost/api. needed if nginx is handling ssl termination
      - PREFECT_LOGGING_LEVEL=DEBUG
    ports:
      - "127.0.0.1:4200:4200"
    depends_on:
      - prefect_db
    networks:
      mle_net:


  prefect_db:
    image: postgres:14.5-alpine
    container_name: prefect-db
    environment:
      - POSTGRES_USER=${PREFECT_DB_USER}
      - POSTGRES_PASSWORD=${PREFECT_DB_PW}
      - POSTGRES_DB=${PREFECT_DB_NAME}
    volumes:
      - ./data/prefect_db:/var/lib/postgresql/data:rw
    restart: unless-stopped
    networks:
      mle_net:


  tiled:
    # see the file ./tiled/deploy/config.yml for detailed configuration of tiled
    image: ghcr.io/bluesky/tiled:v0.1.0a118
    container_name: tiled-server
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - TILED_DB_USER=${TILED_DB_USER}
      - TILED_DB_PW=${TILED_DB_PW}
      - TILED_DB_NAME=${TILED_DB_NAME}
      - TILED_DB_SERVER=${TILED_DB_SERVER}
      - TILED_SINGLE_USER_API_KEY=${TILED_SINGLE_USER_API_KEY}
    volumes:
      - ./tiled/deploy:/deploy
      - ${READ_DIR}:/tiled_storage
    depends_on:
      - tiled_db
    networks:
      mle_net:


  tiled_db:
    image: postgres:14.5-alpine
    container_name: tiled-db
    environment:
      - POSTGRES_USER=${TILED_DB_USER}
      - POSTGRES_PASSWORD=${TILED_DB_PW}
      - POSTGRES_DB=${TILED_DB_NAME}
    volumes:
      - ./data/tiled_db:/var/lib/postgresql/data:rw
      - ${READ_DIR}:/tiled_storage
    restart: unless-stopped
    networks:
      mle_net:

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.22.0 
    container_name: mlflow-server
    command: >
      /bin/sh -c "pip install --no-cache-dir psycopg2-binary 'mlflow[auth]' &&
      mlflow server
      --backend-store-uri postgresql://${MLFLOW_DB_USER}:${MLFLOW_DB_PW}@mlflow_db:5432/${MLFLOW_DB_NAME}
      --host 0.0.0.0
      --port 5000
      --app-name basic-auth"
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - POSTGRES_USER=${MLFLOW_DB_USER}
      - POSTGRES_PASSWORD=${MLFLOW_DB_PW}
      - POSTGRES_DB=${MLFLOW_DB_NAME}
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
      - MLFLOW_FLASK_SERVER_SECRET_KEY=${MLFLOW_FLASK_SERVER_SECRET_KEY}
      - MLFLOW_AUTH_CONFIG_PATH=/basic_auth.ini
    depends_on:
      - mlflow_db
    networks:
      - mle_net
    volumes:
      - ./data/mlflow_storage:/mlartifacts:rw  # Persist MLflow models, logs, and artifacts
      - ./data/mlflow_auth:/mlflow_auth:rw # Dedicated volume for auth database
      - ./basic_auth.ini:/basic_auth.ini

  mlflow_db:
    image: postgres:14.5-alpine  # Lightweight PostgreSQL version
    container_name: mlflow-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${MLFLOW_DB_USER}
      - POSTGRES_PASSWORD=${MLFLOW_DB_PW}
      - POSTGRES_DB=${MLFLOW_DB_NAME}
    volumes:
      - ./data/mlflow_db:/var/lib/postgresql/data:rw
      - ./data/mlflow_storage:/mlartifacts:rw  # Persist PostgreSQL database
    networks:
      - mle_net

  data_clinic:
    restart: "unless-stopped"
    container_name: "data_clinic"
    build:
      context: "."
    command: "python frontend.py"
    environment:
      # Dash
      APP_HOST: "0.0.0.0"
      APP_PORT: "8070"
      # Data directories
      READ_DIR_MOUNT: "${READ_DIR}"   # Used to mount the read directory in podman jobs
      WRITE_DIR_MOUNT: "${WRITE_DIR}" # Used to mount the write directory in podman jobs
      READ_DIR: "/tiled_storage"
      WRITE_DIR: "/tiled_storage/writable"
      # Tiled
      DEFAULT_TILED_URI: '${DEFAULT_TILED_URI}'
      DATA_TILED_KEY: '${DATA_TILED_KEY}'
      RESULTS_TILED_URI: '${RESULTS_TILED_URI}'
      RESULTS_TILED_API_KEY: '${RESULTS_TILED_API_KEY}'
      # Prefect
      PREFECT_API_URL: '${PREFECT_API_URL}'
      FLOW_NAME: '${FLOW_NAME}'
      TIMEZONE: "${TIMEZONE}"
      PREFECT_TAGS: "${PREFECT_TAGS}"
      CONTAINER_NETWORK: "${CONTAINER_NETWORK}"
      # Slurm jobs
      PARTITIONS_CPU: "${PARTITIONS_CPU}"
      MAX_TIME_CPU: "${MAX_TIME_CPU}"
      RESERVATIONS_CPU: "${RESERVATIONS_CPU}"
      PARTITIONS_GPU: "${PARTITIONS_GPU}"
      RESERVATIONS_GPU: "${RESERVATIONS_GPU}"
      MAX_TIME_GPU: "${MAX_TIME_GPU}"
      SUBMISSION_SSH_KEY: "${SUBMISSION_SSH_KEY}"
      FORWARD_PORTS: "${FORWARD_PORTS}"
      # Mode
      MODE: "development"
      USER: ${USER}
      # MLflow
      MLFLOW_TRACKING_URI: '${MLFLOW_TRACKING_URI}'
      MLFLOW_TRACKING_USERNAME: '${MLFLOW_TRACKING_USERNAME}'
      MLFLOW_TRACKING_PASSWORD: '${MLFLOW_TRACKING_PASSWORD}'
      MLFLOW_CACHE_DIR: "/mlflow_cache"
    volumes:
      - $READ_DIR:/tiled_storage
      - ./src:/app/work/src
      - ./data/mlflow_cache:/mlflow_cache
    ports:
      - 127.0.0.1:8072:8070
    depends_on:
      - mlflow
      - tiled
      - prefect
    networks:
      - mle_net

  autoencoders:
    image: ghcr.io/mlexchange/mlex_pytorch_autoencoders:main

networks:
  mle_net:
    name: mle_net
    driver: bridge

# If services are already running on a different docker compose, use the following network definition
# networks:
#   mle_net:
#     external: true
